-- ============================================================
-- [실행 보류] 범위 제외 테이블 삭제 — 프로젝트 마무리 시점에 실행 (2026-09-30 작성)
-- 근거: UML 01-5 최종(유스케이스 39 -> 26개). 해당 코드(엔티티/API)는 이미 삭제했다(git 태그 pre-scope-cut-20260930 이전에 존재).
-- 공유 서버의 EMERGENCY 스키마이므로 실행 전 팀에 알리고, 아래 1)로 데이터가 없는지 확인할 것.
-- PURGE 를 쓰지 않는다: 휴지통에 남아 실수했을 때 FLASHBACK TABLE ... TO BEFORE DROP 으로 되돌릴 수 있다.
-- ============================================================

-- 1) 삭제 전 건수 확인 (없는 테이블은 ORA-00942 가 나도 무시하고 다음으로)
SELECT 'CONSULT_REQUEST'         AS tbl, COUNT(*) AS cnt FROM EMERGENCY.CONSULT_REQUEST
UNION ALL SELECT 'ONCALL_REQUEST',            COUNT(*) FROM EMERGENCY.ONCALL_REQUEST
UNION ALL SELECT 'SURGERY_ORDER_STATUS_REF',  COUNT(*) FROM EMERGENCY.SURGERY_ORDER_STATUS_REF
UNION ALL SELECT 'AMBULANCE_TRANSPORT',       COUNT(*) FROM EMERGENCY.AMBULANCE_TRANSPORT
UNION ALL SELECT 'EQUIPMENT_ALLOCATION',      COUNT(*) FROM EMERGENCY.EQUIPMENT_ALLOCATION
UNION ALL SELECT 'EQUIPMENT',                 COUNT(*) FROM EMERGENCY.EQUIPMENT;

-- 2) 삭제 (자식 테이블 먼저: EQUIPMENT_ALLOCATION -> EQUIPMENT)
DROP TABLE EMERGENCY.CONSULT_REQUEST;
DROP TABLE EMERGENCY.ONCALL_REQUEST;
DROP TABLE EMERGENCY.SURGERY_ORDER_STATUS_REF;
DROP TABLE EMERGENCY.AMBULANCE_TRANSPORT;
DROP TABLE EMERGENCY.EQUIPMENT_ALLOCATION;
DROP TABLE EMERGENCY.EQUIPMENT;

-- 3) 코드에 있던 응급업무코드 테이블은 DB에 만든 적이 없을 수 있다. 있는 경우에만 삭제(EMG_CODE 먼저)
-- DROP TABLE EMERGENCY.EMG_CODE;
-- DROP TABLE EMERGENCY.EMG_CODE_GROUP;

-- 되돌리기(휴지통에 있을 때): FLASHBACK TABLE EMERGENCY.EQUIPMENT TO BEFORE DROP;
