-- ============================================================
-- 코드값을 admin 관례(숫자 2자리)로 바꾸는 데이터 정리 — 2026-09-30 결정 (03 작업기록 1-3장)
-- 새 코드(숫자 값)를 배포하는 시점에 함께 실행할 것. 새 코드가 떠 있는데 이 스크립트를 안 돌리면
-- 병상 상태 집계·KTAS 표시 등이 옛 값(EMPTY, '1' ...)을 못 알아본다.
-- 대상: EMERGENCY 스키마의 기존 테스트/시드 데이터. 이미 숫자인 값은 건드리지 않는다(WHERE ... IN 으로 옛 값만).
-- 실행 후 마지막 점검 쿼리에서 "옛 값이 남은 행" 이 0건이어야 한다. 실행 계정: EMERGENCY.
-- ============================================================

-- 병상: 구역 / 유형 / 상태
UPDATE EMERGENCY.BED SET ZONE_CODE = CASE ZONE_CODE
    WHEN 'RESUS' THEN '01' WHEN 'CRITICAL' THEN '02' WHEN 'URGENT' THEN '03'
    WHEN 'FAST_TRACK' THEN '04' WHEN 'PEDIATRIC' THEN '05' WHEN 'ISOLATION' THEN '06' END
 WHERE ZONE_CODE IN ('RESUS','CRITICAL','URGENT','FAST_TRACK','PEDIATRIC','ISOLATION');
UPDATE EMERGENCY.BED SET BED_TYPE_CODE = CASE BED_TYPE_CODE
    WHEN 'GENERAL' THEN '01' WHEN 'TREATMENT' THEN '02' WHEN 'ISOLATION_ROOM' THEN '03' END
 WHERE BED_TYPE_CODE IN ('GENERAL','TREATMENT','ISOLATION_ROOM');
UPDATE EMERGENCY.BED SET BED_STATUS_CODE = CASE BED_STATUS_CODE
    WHEN 'EMPTY' THEN '01' WHEN 'OCCUPIED' THEN '02' WHEN 'CLEANING' THEN '03' WHEN 'OUT_OF_SERVICE' THEN '04' END
 WHERE BED_STATUS_CODE IN ('EMPTY','OCCUPIED','CLEANING','OUT_OF_SERVICE');

-- 중증도 평가: KTAS 등급('1'~'5' -> '01'~'05'), 평가 종류
UPDATE EMERGENCY.TRIAGE_ASSESSMENT SET KTAS_LEVEL_CODE = '0' || KTAS_LEVEL_CODE
 WHERE KTAS_LEVEL_CODE IN ('1','2','3','4','5');
UPDATE EMERGENCY.TRIAGE_ASSESSMENT SET ASSESSMENT_TYPE_CODE = CASE ASSESSMENT_TYPE_CODE
    WHEN 'INITIAL' THEN '01' WHEN 'REASSESS' THEN '02' END
 WHERE ASSESSMENT_TYPE_CODE IN ('INITIAL','REASSESS');

-- 격리 유형
UPDATE EMERGENCY.ISOLATION_ASSESSMENT SET ISOLATION_TYPE_CODE = CASE ISOLATION_TYPE_CODE
    WHEN 'CONTACT' THEN '01' WHEN 'DROPLET' THEN '02' WHEN 'AIRBORNE' THEN '03' WHEN 'PROTECTIVE' THEN '04' END
 WHERE ISOLATION_TYPE_CODE IN ('CONTACT','DROPLET','AIRBORNE','PROTECTIVE');

-- 위험 스크리닝: 종류 / 결과
UPDATE EMERGENCY.RISK_SCREENING SET SCREENING_TYPE_CODE = CASE SCREENING_TYPE_CODE
    WHEN 'SEPSIS' THEN '01' WHEN 'STROKE' THEN '02' END
 WHERE SCREENING_TYPE_CODE IN ('SEPSIS','STROKE');
UPDATE EMERGENCY.RISK_SCREENING SET RESULT_CODE = CASE RESULT_CODE
    WHEN 'NEGATIVE' THEN '01' WHEN 'POSITIVE' THEN '02' WHEN 'INCONCLUSIVE' THEN '03' END
 WHERE RESULT_CODE IN ('NEGATIVE','POSITIVE','INCONCLUSIVE');

-- 퇴실 결정 (옛 테스트값 DISCHARGE 는 귀가와 같은 뜻이라 01)
UPDATE EMERGENCY.DISPOSITION SET DISPOSITION_TYPE_CODE = CASE DISPOSITION_TYPE_CODE
    WHEN 'HOME' THEN '01' WHEN 'DISCHARGE' THEN '01' WHEN 'ADMIT' THEN '02' WHEN 'TRANSFER' THEN '03'
    WHEN 'DEATH' THEN '04' WHEN 'DAMA' THEN '05' END
 WHERE DISPOSITION_TYPE_CODE IN ('HOME','DISCHARGE','ADMIT','TRANSFER','DEATH','DAMA');

-- 진료기록 종류
UPDATE EMERGENCY.CLINICAL_NOTE SET NOTE_TYPE_CODE = CASE NOTE_TYPE_CODE
    WHEN 'INITIAL' THEN '01' WHEN 'REASSESSMENT' THEN '02' WHEN 'PROCEDURE' THEN '03' WHEN 'DISCHARGE_SUMMARY' THEN '04' END
 WHERE NOTE_TYPE_CODE IN ('INITIAL','REASSESSMENT','PROCEDURE','DISCHARGE_SUMMARY');

-- 동의 기록: 종류는 수술(01)·마취(02)·침습적 시술(05)만 쓴다. 수혈/개인정보 활용은 대응 값이 없다.
UPDATE EMERGENCY.CONSENT_RECORD SET CONSENT_TYPE_CODE = CASE CONSENT_TYPE_CODE
    WHEN 'SURGERY' THEN '01' WHEN 'ANESTHESIA' THEN '02' WHEN 'PROCEDURE' THEN '05' END
 WHERE CONSENT_TYPE_CODE IN ('SURGERY','ANESTHESIA','PROCEDURE');
UPDATE EMERGENCY.CONSENT_RECORD SET CONSENT_STATUS_CODE = CASE CONSENT_STATUS_CODE
    WHEN 'AGREED' THEN '01' WHEN 'REFUSED' THEN '02' WHEN 'DEFERRED' THEN '03' END
 WHERE CONSENT_STATUS_CODE IN ('AGREED','REFUSED','DEFERRED');
UPDATE EMERGENCY.CONSENT_RECORD SET CONSENTED_BY_CODE = CASE CONSENTED_BY_CODE
    WHEN 'SELF' THEN '01' WHEN 'GUARDIAN' THEN '02' END
 WHERE CONSENTED_BY_CODE IN ('SELF','GUARDIAN');
-- 테스트로 넣었던 수혈/개인정보 활용 행(기록자 test-verify)은 새 종류에 없으므로 지운다. 실제 데이터라면 이 줄을 실행하지 말고 확인할 것.
DELETE FROM EMERGENCY.CONSENT_RECORD WHERE RECORDED_BY_ID = 'test-verify' AND CONSENT_TYPE_CODE IN ('TRANSFUSION','PRIVACY');

-- 입원요청: 상태 / 진료과(옛 테스트값 INTERNAL_MEDICINE -> DEPT_CD 01)
UPDATE EMERGENCY.ADMISSION_REQUEST SET REQUEST_STATUS_CODE = CASE REQUEST_STATUS_CODE
    WHEN 'REQUESTED' THEN '01' WHEN 'BED_ASSIGNED' THEN '02' WHEN 'ADMISSION_REJECTED' THEN '03' END
 WHERE REQUEST_STATUS_CODE IN ('REQUESTED','BED_ASSIGNED','ADMISSION_REJECTED');
UPDATE EMERGENCY.ADMISSION_REQUEST SET TARGET_DEPT_CODE = '01' WHERE TARGET_DEPT_CODE = 'INTERNAL_MEDICINE';

-- 전원 소견서: 옛 테스트값 SEOUL_HOSP -> 기타 병원(06)
UPDATE EMERGENCY.TRANSFER_NOTE SET TARGET_HOSPITAL_CODE = '06' WHERE TARGET_HOSPITAL_CODE = 'SEOUL_HOSP';

COMMIT;

-- ------------------------------------------------------------
-- 점검: 아래는 모두 0건이어야 한다 (옛 값이 남은 행)
-- ------------------------------------------------------------
SELECT 'BED' AS tbl, COUNT(*) AS old_rows FROM EMERGENCY.BED
 WHERE ZONE_CODE NOT IN ('01','02','03','04','05','06') OR BED_TYPE_CODE NOT IN ('01','02','03') OR BED_STATUS_CODE NOT IN ('01','02','03','04')
UNION ALL SELECT 'TRIAGE_ASSESSMENT', COUNT(*) FROM EMERGENCY.TRIAGE_ASSESSMENT
 WHERE KTAS_LEVEL_CODE NOT IN ('01','02','03','04','05') OR ASSESSMENT_TYPE_CODE NOT IN ('01','02')
UNION ALL SELECT 'ISOLATION_ASSESSMENT', COUNT(*) FROM EMERGENCY.ISOLATION_ASSESSMENT WHERE ISOLATION_TYPE_CODE NOT IN ('01','02','03','04')
UNION ALL SELECT 'RISK_SCREENING', COUNT(*) FROM EMERGENCY.RISK_SCREENING
 WHERE SCREENING_TYPE_CODE NOT IN ('01','02') OR (RESULT_CODE IS NOT NULL AND RESULT_CODE NOT IN ('01','02','03'))
UNION ALL SELECT 'DISPOSITION', COUNT(*) FROM EMERGENCY.DISPOSITION WHERE DISPOSITION_TYPE_CODE NOT IN ('01','02','03','04','05')
UNION ALL SELECT 'CLINICAL_NOTE', COUNT(*) FROM EMERGENCY.CLINICAL_NOTE WHERE NOTE_TYPE_CODE IS NOT NULL AND NOTE_TYPE_CODE NOT IN ('01','02','03','04')
UNION ALL SELECT 'CONSENT_RECORD', COUNT(*) FROM EMERGENCY.CONSENT_RECORD
 WHERE CONSENT_TYPE_CODE NOT IN ('01','02','05') OR CONSENT_STATUS_CODE NOT IN ('01','02','03') OR CONSENTED_BY_CODE NOT IN ('01','02')
UNION ALL SELECT 'ADMISSION_REQUEST', COUNT(*) FROM EMERGENCY.ADMISSION_REQUEST WHERE REQUEST_STATUS_CODE NOT IN ('01','02','03');
